# Generated by Django 5.0.1 on 2024-06-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_alter_apartmentimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentimage',
            name='image',
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
